### ISSUE TITLE
Broken link for "Catalog GUI Example"

### ISSUE THREAD

**Issue by pmiddend** [SciCatProject/scicatproject.github.io#13]
To reproduce, simply:

- go to https://scicatproject.github.io/
- click on "Catalog GUI Example"

The target, https://scicat.esss.dk/ doesn't have a DNS entry (anymore?).

Edit: https://scicat.ess.dk/ (one 's' less) at least is 404. :)

**Comment by stephan271** [comment]
Thanks for pointing out, Tobias has corrected this and the Catalog Example GUI link now points to a new URL https://scicat.ess.eu
