### ISSUE TITLE
Change releases name.

### ISSUE THREAD

**Issue by nitrosx** [SciCatProject/scicatproject.github.io#39]
In the current version, we name the releases by the assigned versions number.
We have decided to move away from this and name the current efforts with an indicative name.
The releases info to be posted:
- Release Jobs, 
Complete migration and refactor of jobs in backend v4.x
https://github.com/orgs/SciCatProject/projects/3
Leader: Daphne Van Dijken

- Release Elastic Search, 
Integrate Elastic Search with SciCat
https://github.com/orgs/SciCatProject/projects/7
Leader: Max Novelli

- Release Search IU,
Improving usability of frontend search UI and add needed functionality to backend
https://github.com/orgs/SciCatProject/projects/5
Leader: Igor Khokhriakov

**Comment by despadam** [comment]
Hi @nitrosx, the current list of efforts also contains the following two. Would you like that we still keep them? Or to delete them and only keep the ones you menioned above?

- pySciCat,
Low level python library that offers each endpoint as function in python. It requires a good level of knowledge of SciCat backend. Suggested for developing third party applications that will interface with SciCat, like data ingestors, dedicated custom UIs, or ETL processes retrieving data from and storing results in SciCat
https://github.com/SciCatProject/pyscicat
- Scitacean,
High level python library hiding all the inner intricacies of SciCat. It is designed for users concentrating on data analysis, exploratory tasks. It allows the user to transparently retrieve existing datasets and creating new ones with only few lines of code. It also provide functionalities for data transferring. 
 https://github.com/SciCatProject/scitacean


Also, based on the above, I have updated the roles of team leaders:
- for _Daphne_ to `Release Jobs Leader`
- for _you_ to `Release Elastic Search Leader`

Should I also add _Igor_ to the list as `Release Search UI Leader`?

**Comment by nitrosx** [comment]
@despadam
Could you please keep pySciCat and Scitacean?
You can remove `Release Elastic Search Leader`
Yes, add Igor as `Release Search UI Leader`

Thanks
